# Just the Docs Configuration
remote_theme: just-the-docs/just-the-docs

# Site settings
title: Research Hub
description: "AI調査共有ハブ - ChatGPT/Gemini調査結果をMarkdownで整理・共有"
baseurl: "/research-hub" # GitHub Pagesのサブディレクトリ
url: "https://jokerjunya.github.io"

# Theme settings
color_scheme: light

# Enable heading anchors
heading_anchors: true

# Back to top link
back_to_top: true
back_to_top_text: "ページトップへ"

# Footer content
footer_content: "Copyright &copy; 2025 Research Hub Team. Distributed by an MIT license."

# Collections for organizing content
collections_dir: docs

# Aux links for the upper right navigation
aux_links:
  "GitHub":
    - "https://github.com/jokerjunya/research-hub"

# Search settings
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# GA Tracking (optional)
# ga_tracking: UA-XXXXXXXX-X

# Enable or disable the site search
search_enabled: true

# Callouts
callouts:
  warning:
    title: 注意
    color: red
  note:
    title: 備考
    color: blue
  tip:
    title: ヒント
    color: green

# Plugins
plugins:
  - jekyll-seo-tag

